review_app/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/index'
  # get 'sessions/new'
  resources :sessions
  get 'sessions/create'
  get 'sessions/destroy'
  resources :profiles
  get 'reviews/index'
  get 'reviews/show'
  get 'reviews/new'
  get 'reviews/create'
  get 'reviews/update'
  get 'reviews/edit'
  get 'reviews/destroy'
  get 'static_pages/home'
  root 'static_pages#home'
  get 'static_pages/about'
  get 'static_pages/contact'
  resources   :products
  resources   :reviews do
    collection do
      get :search
    end
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

review_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

review_app/app/models/product.rb
class Product < ApplicationRecord
    has_many   :reviews
end

review_app/app/models/profile.rb
class Profile < ApplicationRecord
  has_secure_password
  validates_uniqueness_of :email
end

review_app/app/models/review.rb
class Review < ApplicationRecord
end

review_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    private
        def current_user
            @current_user ||=Profile.find(session[ :profile_id]) if session[ :profile_id]
        end
    
    def authorize
        redirect_to new_session_path, alert: 'Please Log in or Sign up' if current_user.nil?
    end
    helper_method :current_user
end

review_app/app/controllers/products_controller.rb
class ProductsController < ApplicationController

def index
    @products=Product.all
end

def new
end

def show
    @product=Product.find(params[:id])
end

def create
    @product=Product.new(product_params)
    @product.save
    redirect_to @product
end
private
    def product_params
        params.require(:product).permit(:name, :brand, :cost, :category, :date, :description)
    end



end

review_app/app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController

    def new
        @profile=Profile.new

    end
    def index
        @profile = current_user
    
    end
    def create
        @profile=Profile.new(profile_params)
            if @profile.save
                    redirect_to static_pages_home_path, notice:
                    "Welcome #{@profile.fname}! to Ben's Tech Reviews"
            else
                    render 'new'
            end
    end
    def update
        @profile = Profile.find(params[:id])
        if @profile.update(profile_params)
          redirect_to static_pages_home_path
        else
        render 'edit'
        end
      
    
    end
    private
        def profile_params
            params.require(:profile).permit(:email, :password, :fname, :dob, :address, :city, :country, :password_confirmation)
        end



end

review_app/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authorize, :only => [ :create]
  def index
    @reviews = Review.all
    @products = Product.all
  end

  def show
    @review=Review.find(params[:id])
  end

  def new
  end

  def create
    @review=Review.new(review_params)
      if @review.save
      redirect_to reviews_path, notice:
      "You have successfully created a Review"

      else
        redirect_to reviews_path, alert:
        "You will need to sign in to create a review"
      end
  end

  def update
    @review = Review.find(params[:id])
    if @review.update(review_params)
      redirect_to @review
    else
    render 'edit'
    end
  end

  def edit
    @review = Review.find(params[:id])
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to reviews_path
  end
  def search
    @reviews = if params[:term]
      Review.where('product_id LIKE ?', "%#{params[:term]}")
     else
      Review.all
    end
  end 
  private
    def review_params
        params.require(:review).permit(:author, :product_id, :rating, :content, :date)
    end

end

review_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    redirect_to root_path
  end

  def new
  end

  def create
    profile=Profile.find_by_email(params[ :email])
    if profile && profile.authenticate(params[ :password])
      session[ :profile_id]=profile.id
      redirect_to root_path, notice:
      "Welcome #{profile.fname}, you are now logged in"
    else
      render 'new', alert:
      "Invalid username and/or password"
      end
  end

  def destroy
    session[:profile_id] = nil
    redirect_to root_path, notice:
     "You have successfully logged out"
  end
end

review_app/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

review_app/app/helpers/application_helper.rb
module ApplicationHelper
end

review_app/app/helpers/products_helper.rb
module ProductsHelper
end

review_app/app/helpers/profiles_helper.rb
module ProfilesHelper
end

review_app/app/helpers/reviews_helper.rb
module ReviewsHelper
end

review_app/app/helpers/sessions_helper.rb
module SessionsHelper
end

review_app/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

review_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReviewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  

   <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">

      <h5 class="my-0 mr-md-auto font-weight-normal"> Bens Tech Review </h5>

      <nav class="my-2 my-md-0 mr-md-3">


        <a class="p-2 text-dark" href="#"> <%= link_to "Home", static_pages_home_path %> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "About Us", static_pages_about_path %> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "Contact Us", static_pages_contact_path %> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "Reviews", reviews_path %> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "Add New Review", new_review_path %> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to "Create Account", new_profile_path %> </a>
        <% if current_user %>
        <a class="p-2 text-dark" href="#">
        <%= link_to 'Log out', session_path('active'), method: :delete %> </a>
        <a class="p-2 text-dark" href="#"> <%= link_to current_user.fname, profiles_path(session) %> </a>
        <% else %>
        <a class="p-2 text-dark" href="#">
        <%= link_to 'Log in', new_session_path, class: "active_nav_link" %>
        </a>
       <% end %>
      </nav>

    </div>
    
    <div class="container">
    <%= yield %>
    </div>   
  </body>
</html>

review_app/app/views/products/index.html.erb
<div class="container">
<h2> All Products </h2>
<table border="1" class="table">

<tr>
    <th> Product Name </th>
    <th> Category </th>
    <th> Cost </th>
    <th> Product Page </th>
</tr>

<% @products.each do |product| %>

<tr>
<td> <%= product.name %> </td>
<td> <%= product.category %> </td>
<td> <%= product.cost %> </td>
<td> <%= link_to 'Product Page', product_path(product) %> </td>

</tr>
<%= link_to 'Add New Products', new_product_path %>
<% end %>
</table>
</div>

review_app/app/views/products/new.html.erb
<div class="container">
<h1> Add New Product </h1>

<%= form_for :product, url: products_path do |f| %>
<div class="form-group">
<%= f.label :name %>
<%= f.text_field :name %>
</div> 

<div class="form-group">
<%= f.label :brand %>
<%= f.text_field :brand %>
</div>

<div class="form-group">
<%= f.label :cost %>
<%= f.text_field :cost %>
</div>

<div class="form-group">
<%= f.label :category %>
<%= f.text_field :category %>
</div> 

<div class="form-group">
<%= f.label :date %>
<%= f.text_field :date %>
</div> 

<div class="form-group">
<%= f.label :description %>
<%= f.text_area :description %>
</div>

<div class="form-group">
<%= f.submit %>
</div>
<% end %>
</div>

review_app/app/views/products/show.html.erb
<div class="container">
<h3>Product Details</h3>

<p>Product Name: <%= @product.name %> </p>
<p>Product Brand: <%= @product.brand %> </p>
<p>Product Cost: <%= @product.cost %> </p>
<p>Product Category: <%= @product.category %> </p>
<p>Product Date Released: <%= @product.date %> </p>
<p>Product Description: <%= @product.description %> </p>

</div>

review_app/app/views/profiles/edit.html.erb
<div class="container">
<h2>Edit Profile </h2>
<%= form_for current_user do |f| %>

<%= f.text_field :fname, placeholder: 'Enter your Full Name', class:
'form-control' %>
    
<%= f.email_field :email, placeholder: 'Enter your Email', class:
'form-control' %>
    
<%= f.date_field :dob, placeholder: 'Enter your Date of Birth', class:
'form-control' %>
    
<%= f.text_field :address, placeholder: 'Enter your Address', class:
'form-control' %>
    
<%= f.text_field :city, placeholder: 'Enter your City', class:
'form-control' %>
    
<%= f.text_field :country, placeholder: 'Enter your Country', class:
'form-control' %>
    
<%= f.password_field :password, placeholder: 'Change Password',
class: 'form-control' %>
    
<%= f.password_field :password_confirmation, placeholder: 'Confirm
your Password', class: 'form-control' %>
    
</div>
<%= f.submit "Submit", class:'btn btn-primary' %>
    <%=link_to "Cancel", profiles_path, class:'btn btn-default' %>
<% end %>
</div>

review_app/app/views/profiles/index.html.erb
<div class="container">
<h2> Your Profile </h2>
</div>

<p>Full Name: <%= @profile.fname %> </p>
<p>Date Of Birth: <%= @profile.dob %> </p>
<p>Adress: <%= @profile.address %> </p>
<p>City: <%= @profile.city %> </p>
<p>Country: <%= @profile.country %> </p>
<%= link_to 'Edit', edit_profile_path(@profile) %> </td>


</div>

review_app/app/views/profiles/new.html.erb
<div class="container">
    <h2>Create User Account</h2>
<%= form_for @profile do |f| %>

<div class="field" style="100%">
    <% if @profile.errors.any? %>
        <div id="error_explanation">
        <h2>
        <%= pluralize(@profile.errors.count, "error") %>
        prohibted this from being saved:
        </h2>

<p>
    <ul>
        <% @user.errors.full_messages.each do |msg| %>
            <li>
                <%= msg %>
            </li>
        </ul>
    <% end %>
    </p>

<% if alert %>
        <%= alert %>
        <% end %>
    </div>
    <% end %>

<%= f.text_field :fname, placeholder: 'Enter your Full Name', class:
'form-control' %>

<%= f.email_field :email, placeholder: 'Enter your Email', class:
'form-control' %>

<%= f.date_field :dob, placeholder: 'Enter your Date of Birth', class:
'form-control' %>

<%= f.text_field :address, placeholder: 'Enter your Address', class:
'form-control' %>

<%= f.text_field :city, placeholder: 'Enter your City', class:
'form-control' %>

<%= f.text_field :country, placeholder: 'Enter your Country', class:
'form-control' %>

<%= f.password_field :password, placeholder: 'Create a Password',
class: 'form-control' %>

<%= f.password_field :password_confirmation, placeholder: 'Confirm
your Password', class: 'form-control' %>

    <%= f.submit 'Create Account' %>
    <% end %>
</div>
</div>

review_app/app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

review_app/app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

review_app/app/views/reviews/edit.html.erb
<div class="container">
<h2>Edit Review </h2>
<%= form_for @review do |f| %>

<div class="form-group">
    <%= f.label :author %><br />
    <%= f.text_field :author, class:'form-control' %><br />
</div>
<div class="form-group">
    <%= f.label :product %><br />
    <%= f.select :product_id, Product.all.collect {|x| [x.name,
x.id]}, {:include_blank => 'Select Product'},class:'form-control'
%><br /><br />
</div>
<div class="form-group">
    <%= f.label :rating %><br />
    <%= f.text_field :rating, class:'form-control' %><br />
</div>
<div class="form-group">
    <%= f.label :content %><br />
    <%= f.text_area :content, class:'form-control' %><br />
</div>
<div class="form-group">
    <%= f.label :date %><br />
    <%= f.text_area :date, class:'form-control' %><br />
</div>
<%= f.submit "Submit", class:'btn btn-primary' %>
    <%=link_to "Cancel", reviews_path, class:'btn btn-default' %>
<% end %>
</div>

review_app/app/views/reviews/index.html.erb
<div class="container">
<h2> All Reviews </h2>
<table border="1" class="table">

<tr>
    <th> Product </th>
    <th> Author </th>
    <th> Rating </th>
    <th> Date </th>
    <th> Full Review </th>
    <th> Edit</th>
    <th> Delete </th>
</tr>

<% @reviews.each do |review| %>

<tr>
<td> <%= review.product_id %> </td>
<td> <%= review.author %> </td>
<td> <%= review.rating %> </td>
<td> <%= review.date %> </td>
<td> <%= link_to 'See Review', review_path(review) %> </td>
<td> <%= link_to 'Edit', edit_review_path(review) %> </td>
<td> <%= link_to 'Delete', review_path(review),
method: :Delete,
data: {confirm: "Are you sure you want to delete this Review"}
%> </td>

</tr>
<% end %>
</table>
</div>

review_app/app/views/reviews/new.html.erb
<h1>Reviews</h1>

<div class="container">
<h2>Add New Review</h2>
<%= form_for :review, url: reviews_path do |f| %>

<div class="form-group">
    <%= f.label :author %><br />
    <%= f.text_field :author, class:'form-control' %><br />
</div>
<div class="form-group">
    <%= f.label :product %><br />
    <%= f.select :product_id, Product.all.collect {|x| [x.name]}, {:include_blank => 'Select Product'},class:'form-control'
%><br /><br />
</div>
<div class="form-group">
    <%= f.label :rating %><br />
    <%= f.text_field :rating, class:'form-control' %><br />
</div>
<div class="form-group">
    <%= f.label :content %><br />
    <%= f.text_area :content, class:'form-control' %><br />
</div>
<div class="form-group">
    <%= f.label :date %><br />
    <%= f.text_area :date, class:'form-control' %><br />
</div>
<%= f.submit "Submit", class:'btn btn-primary' %>
    <%=link_to "Cancel", reviews_path, class:'btn btn-default' %>
<% end %>
</div>

review_app/app/views/reviews/search.html.erb
<div class="container">
<%= form_tag search_reviews_path, method: :get do %>
    <%= text_field_tag :term, nil, placeholder: 'Search',
class:'form-control' %>
<%= submit_tag "Search", class:'btn btn-default' %>
<% end %>
    
<h2> All Reviews </h2>
<table border="1" class="table">

<tr>
    <th> Product </th>
    <th> Author </th>
    <th> Rating </th>
    <th> Date </th>
    <th> Full Review </th>
    <th> Edit</th>
    <th> Delete </th>
</tr>

<% @reviews.each do |review| %>

<tr>
<td> <%= review.product_id %> </td>
<td> <%= review.author %> </td>
<td> <%= review.rating %> </td>
<td> <%= review.date %> </td>
<td> <%= link_to 'See Review', review_path(review) %> </td>
<td> <%= link_to 'Edit', edit_review_path(review) %> </td>
<td> <%= link_to 'Delete', review_path(review),
method: :Delete,
data: {confirm: "Are you sure you want to delete this Review"}
%> </td>

</tr>
<% end %>
</table>
</div>

review_app/app/views/reviews/show.html.erb
<div class="container">
<h3>Full Review</h3>

<p>Author: <%= @review.author %> </p>
<p>Product: <%= @review.product_id %> </p>
<p>Product Rating: <%= @review.rating %> </p>
<p>The Review: <%= @review.content %> </p>
<p>Date: <%= @review.date %> </p>


</div>

review_app/app/views/reviews/update.html.erb
<h1>Reviews#update</h1>
<p>Find me in app/views/reviews/update.html.erb</p>

review_app/app/views/static_pages/about.html.erb
<h1>About Us</h1>
<div class="container">
<div class="container">
 <div class="row">
 <div class="col">
 <h2> Who Are we? </h2>
 <p> Lorem ipsum dolor sit amet, dicant sanctus similique an vim, quo ea utroque pericula theophrastus, te per omnis definiebas conclusionemque. 
 Ne ipsum paulo eam, mentitum deleniti epicurei ad vis. Ne probo aperiam fabulas vim. 
 Latine commune phaedrum has cu, vix ceteros posidonium id, his at adipisci theophrastus suscipiantur. 
 Id sit choro vituperatoribus. Mea ei posse oporteat. 
 Graeco doctus assentior ex mei, nam id omnis nostrud quaerendum. </p>
 </div>
 <div class="col">
 <p> Animal dolores disputando at duo, labore graecis pericula ad eos. Pri facete praesent ne. 
 Quando soleat altera et duo, ei vim stet legere vocibus. 
 Tractatos comprehensam vim eu, eos at vero illum dictas. </p>
 </div>
 </div></div>

review_app/app/views/static_pages/contact.html.erb
<div class="container">
  <form action="action_page.php">

    <label for="fname">Full Name</label>
    <input type="text" id="fname" name="Fullname" placeholder="Your name..">

    <label for="lname">Email</label>
    <input type="text" id="email" name="email" placeholder="Email..">

    <label for="country">Address</label>
    <input type="text" id="address" name="address" placeholder="Address.">

    <label for="country">Subject Line</label>
    <input type="text" id="subline" name="subline" placeholder="Subject Line">

    <label for="subject">Subject</label>
    <textarea id="subject" name="subject" placeholder="Write something.." style="height:200px"></textarea>

    <input type="submit" value="Submit">

  </form>
</div>

review_app/app/views/static_pages/home.html.erb
<div class="container">
   <h1 class="jumbotron-heading">Welcome</h1>
<div class="container">
 <div class="row">
 <div class="col">
 <h2> Latest News </h2>
 <p> Lorem ipsum dolor sit amet, dicant sanctus similique an vim, quo ea utroque pericula theophrastus, te per omnis definiebas conclusionemque. 
 Ne ipsum paulo eam, mentitum deleniti epicurei ad vis. Ne probo aperiam fabulas vim. 
 Latine commune phaedrum has cu, vix ceteros posidonium id, his at adipisci theophrastus suscipiantur. 
 Id sit choro vituperatoribus. Mea ei posse oporteat. 
 Graeco doctus assentior ex mei, nam id omnis nostrud quaerendum. </p>
 </div>
 <div class="col">
 <h2> Review of the Week </h2>
 <p> Animal dolores disputando at duo, labore graecis pericula ad eos. Pri facete praesent ne. 
 Quando soleat altera et duo, ei vim stet legere vocibus. 
 Tractatos comprehensam vim eu, eos at vero illum dictas. </p>
 </div>
 </div></div>